/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prefixadventure;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhamad Dio
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    int waktu;
    int nyawa;
    int quizke;
    int bintang;
    SelectLevel lvl;
    
    int secondsPassed = 0;
        
        Timer myTimer = new Timer();
        TimerTask task = new TimerTask(){
            public  void run(){
                secondsPassed++;
                WaktuGame.setText(String.valueOf(secondsPassed)); 
                WaktuGameHasil.setText(String.valueOf(secondsPassed));
                }
        };
        
        public void start (){
            myTimer.scheduleAtFixedRate(task,1000,1000);
        }
        public void stop(){
            myTimer.cancel();
        }
    
    public Game(SelectLevel lvl,int quizke) {
        initComponents();
        
        this.start();
        
        nyawa = 3;
        
        this.quizke = quizke;
        System.out.println(quizke);
        this.lvl = lvl;
        
        Hasil.setVisible(false);
        Bintang.setVisible(false);
        WaktuGameHasil.setVisible(false);
        Next.setVisible(false);
        Exit.setVisible(false);
        Quiz1.setVisible(false);
        Quiz2.setVisible(false);
        Quiz3.setVisible(false);
        Quiz4.setVisible(false);
        Quiz5.setVisible(false);
        Quiz6.setVisible(false);
        Quiz7.setVisible(false);
        Quiz8.setVisible(false);
        Quiz9.setVisible(false);
        Quiz10.setVisible(false);
       
        switch(quizke){
            case 1:
                
                Quiz1.setVisible(true);
                
                break;
            case 2:
                
                Quiz2.setVisible(true);
                
                break;
            case 3:
                
                Quiz3.setVisible(true);
                
                break;
            case 4:
                
                Quiz4.setVisible(true);
                
                break;
            case 5:
                
                Quiz5.setVisible(true);
                
                break;
            case 6:
                
                Quiz6.setVisible(true);
                
                break;
            case 7:
                
                Quiz7.setVisible(true);
                
                break;
            case 8:
                
                Quiz8.setVisible(true);
                
                break;
            case 9:
                
                Quiz9.setVisible(true);
                
                break;
            case 10:
                
                Quiz10.setVisible(true);
                
                break;    
        }
    }
    // A Utility Function to find the common prefix between 
// strings- str1 and str2 
	static String commonPrefixUtil(String str1, String str2) { 
		String result = ""; 
		int n1 = str1.length(), n2 = str2.length(); 

		for (int i = 0, j = 0; i <= n1 - 1 && 
				j <= n2 - 1; i++, j++) { 
			if (str1.charAt(i) != str2.charAt(j)) { 
				break; 
			} 
			result += str1.charAt(i); 
		} 
		return (result); 
	} 

// A Divide and Conquer based function to find the 
// longest common prefix. This is similar to the 
// merge sort technique 
	static String commonPrefix(String arr[], int low, int high) { 
		if (low == high) { 
			return (arr[low]); 
		} 

		if (high > low) { 
			// Same as (low + high)/2, but avoids overflow for 
			// large low and high 
			int mid = low + (high - low) / 2; 

			String str1 = commonPrefix(arr, low, mid); 
			String str2 = commonPrefix(arr, mid + 1, high); 

			return (commonPrefixUtil(str1, str2)); 
		} 
		return null; 
	} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Next = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        WaktuGameHasil = new javax.swing.JLabel();
        Bintang = new javax.swing.JLabel();
        WaktuGame = new javax.swing.JLabel();
        AlasTimer = new javax.swing.JLabel();
        Hasil = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();
        Quiz10 = new javax.swing.JLabel();
        Quiz9 = new javax.swing.JLabel();
        Quiz8 = new javax.swing.JLabel();
        Quiz7 = new javax.swing.JLabel();
        Quiz6 = new javax.swing.JLabel();
        Quiz5 = new javax.swing.JLabel();
        Quiz4 = new javax.swing.JLabel();
        Quiz3 = new javax.swing.JLabel();
        Quiz2 = new javax.swing.JLabel();
        Quiz1 = new javax.swing.JLabel();
        Nyawa2 = new javax.swing.JLabel();
        Nyawa3 = new javax.swing.JLabel();
        Nyawa1 = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();
        AlasNyawa = new javax.swing.JLabel();
        MainMenu = new javax.swing.JLabel();
        Go = new javax.swing.JLabel();
        AlasTextField = new javax.swing.JLabel();
        Papan = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NextMouseReleased(evt);
            }
        });
        jPanel1.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 710, 280, 110));

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitMouseReleased(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 90, 70));

        WaktuGameHasil.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        WaktuGameHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(WaktuGameHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 565, 130, 50));

        Bintang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/3Star.png"))); // NOI18N
        jPanel1.add(Bintang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        WaktuGame.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        WaktuGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(WaktuGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, 130, 50));

        AlasTimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Time.png"))); // NOI18N
        jPanel1.add(AlasTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, -1, -1));

        Hasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/BGHasilComplete.png"))); // NOI18N
        jPanel1.add(Hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1024));

        TextField.setBackground(new java.awt.Color(71, 29, 6));
        TextField.setFont(new java.awt.Font("Ubuntu Mono", 3, 72)); // NOI18N
        TextField.setForeground(new java.awt.Color(255, 255, 255));
        TextField.setText("INPUT HERE!");
        TextField.setBorder(null);
        TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldFocusLost(evt);
            }
        });
        jPanel1.add(TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 900, 390, 80));

        Quiz10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz10.png"))); // NOI18N
        jPanel1.add(Quiz10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 789, 483));

        Quiz9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz9.png"))); // NOI18N
        jPanel1.add(Quiz9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 789, 483));

        Quiz8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz8.png"))); // NOI18N
        jPanel1.add(Quiz8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 938, 488));

        Quiz7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz7.png"))); // NOI18N
        jPanel1.add(Quiz7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 938, 488));

        Quiz6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz6.png"))); // NOI18N
        jPanel1.add(Quiz6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 1013, 256));

        Quiz5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz5.png"))); // NOI18N
        jPanel1.add(Quiz5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 1013, 256));

        Quiz4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz4.png"))); // NOI18N
        jPanel1.add(Quiz4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 990, 331));

        Quiz3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz3.png"))); // NOI18N
        jPanel1.add(Quiz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 990, 331));

        Quiz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz2.png"))); // NOI18N
        jPanel1.add(Quiz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 887, 419));

        Quiz1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Quiz1.png"))); // NOI18N
        jPanel1.add(Quiz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 887, 419));

        Nyawa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Nyawa.png"))); // NOI18N
        jPanel1.add(Nyawa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 45, -1, -1));

        Nyawa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Nyawa.png"))); // NOI18N
        jPanel1.add(Nyawa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 45, -1, -1));

        Nyawa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Nyawa.png"))); // NOI18N
        jPanel1.add(Nyawa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 45, -1, -1));

        MainTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/TitleMain_1.png"))); // NOI18N
        jPanel1.add(MainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 461, 351));

        AlasNyawa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/PapanNyawa.png"))); // NOI18N
        jPanel1.add(AlasNyawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 260, 97));

        MainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/MenuMain.png"))); // NOI18N
        MainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MainMenuMouseReleased(evt);
            }
        });
        jPanel1.add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 272, 95));

        Go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Go.png"))); // NOI18N
        Go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Go.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GoMouseReleased(evt);
            }
        });
        jPanel1.add(Go, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 880, 324, 108));

        AlasTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/AlasTextField.png"))); // NOI18N
        jPanel1.add(AlasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 880, 485, 115));

        Papan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/PapanBermain.png"))); // NOI18N
        jPanel1.add(Papan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1227, 732));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/BGSoal1.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1024));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -100000, 320, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldFocusGained
        if(TextField.getText().equals("INPUT HERE!")){
            TextField.setText("");
            TextField.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_TextFieldFocusGained

    private void TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldFocusLost
        if(TextField.getText().equals("")){
            TextField.setText("INPUT HERE!");
            TextField.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_TextFieldFocusLost

    private void GoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoMouseClicked
         
    }//GEN-LAST:event_GoMouseClicked

    private void GoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoMouseReleased
       
        switch(quizke){
            case 1 : 
                String arr[] = {"merah", "meja"};
		int n = arr.length; 
                
		String ans = commonPrefix(arr, 0, n - 1); 
                
                String jawaban = TextField.getText();
                
                if(jawaban.equalsIgnoreCase(ans)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 2 :
                String arr2[] = {"sarung", "sapi"};
		int n2 = arr2.length; 
                
		String ans2 = commonPrefix(arr2, 0, n2 - 1); 
                
                String jawaban2 = TextField.getText();
                
                if(jawaban2.equalsIgnoreCase(ans2)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
            
                break;
            
            case 3 :
                String arr3[] = {"buku", "bulan", "buaya"};
		int n3 = arr3.length; 
                
		String ans3 = commonPrefix(arr3, 0, n3 - 1); 
                System.out.println(ans3);
                String jawaban3 = TextField.getText();
                
                if(jawaban3.equalsIgnoreCase(ans3)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 4 :
                String arr4[] = {"capung", "cabe", "cacing"};
		int n4 = arr4.length; 
                
		String ans4 = commonPrefix(arr4, 0, n4 - 1); 
                
                String jawaban4 = TextField.getText();
                
                if(jawaban4.equalsIgnoreCase(ans4)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 5 :
                String arr5[] = {"mata", "matahari", "matematika", "materai"};
		int n5 = arr5.length; 
                
		String ans5 = commonPrefix(arr5, 0, n5 - 1); 
                
                String jawaban5 = TextField.getText();
                
                if(jawaban5.equalsIgnoreCase(ans5)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 6 :
                String arr6[] = {"belok", "belalang", "belajar", "belanja"};
		int n6 = arr6.length; 
                
		String ans6 = commonPrefix(arr6, 0, n6 - 1); 
                
                String jawaban6 = TextField.getText();
                
                if(jawaban6.equalsIgnoreCase(ans6)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 7 :
                String arr7[] = {"rambut", "rambutan", "ramadhan", "ramalan", "ramayana"};
		int n7 = arr7.length; 
                
		String ans7 = commonPrefix(arr7, 0, n7 - 1); 
                
                String jawaban7 = TextField.getText();
                
                if(jawaban7.equalsIgnoreCase(ans7)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 8 :
                String arr8[] = {"taman", "tamiya", "tambang", "tambak", "tambah"};
		int n8 = arr8.length; 
                
		String ans8 = commonPrefix(arr8, 0, n8 - 1); 
                
                String jawaban8 = TextField.getText();
                
                if(jawaban8.equalsIgnoreCase(ans8)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 9 :
                String arr9[] = {"kalung", "kali", "kaldu", "kalsium", "kalender", "kalau"};
		int n9 = arr9.length; 
                
		String ans9 = commonPrefix(arr9, 0, n9 - 1); 
                
                String jawaban9 = TextField.getText();
                
                if(jawaban9.equalsIgnoreCase(ans9)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
                }
                
                break;
            
            case 10 :
                String arr10[] = {"selai", "selamat", "selang", "seledri", "selimut", "selada"};
		int n10 = arr10.length; 
                
		String ans10 = commonPrefix(arr10, 0, n10 - 1); 
                
                String jawaban10 = TextField.getText();
                
                if(jawaban10.equalsIgnoreCase(ans10)){
                    Hasil.setVisible(true);
                    Bintang.setVisible(true);
                    Next.setVisible(true);
                    Exit.setVisible(true);
                    WaktuGameHasil.setVisible(true);
                    this.stop();
                    
                    if(secondsPassed<10){
                        bintang = 3;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/3Star.png"));
                        Bintang.setIcon(II);
                    }
                    else if(secondsPassed>10 && secondsPassed<20){
                        bintang = 2;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/2Star.png"));
                        Bintang.setIcon(II);
                    }
                    else{
                        bintang = 1;
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/1Star.png"));
                        Bintang.setIcon(II);
                    }
                }
                else{
                    nyawa = nyawa-1;
                    bintang = 0;
                    
                    if(nyawa==2){
                        Nyawa1.setVisible(false);
                    }
                    else if(nyawa==1){
                        Nyawa2.setVisible(false);
                    }
                    else{
                        Nyawa3.setVisible(false);
                        ImageIcon II = new ImageIcon(getClass().getResource("/Background/BGHasilFailed.png"));
                        Hasil.setIcon(II);
                        Hasil.setVisible(true);
                        Bintang.setVisible(true);
                        Next.setVisible(true);
                        WaktuGameHasil.setVisible(true);
                        Exit.setVisible(true);
                        this.stop();
                    }
            
                break;
            
        }
    }
        
    }//GEN-LAST:event_GoMouseReleased

    private void MainMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuMouseReleased
        dispose();
        
        nyawa = 3;
        
        Nyawa1.setVisible(true);
        Nyawa2.setVisible(true);
        Nyawa3.setVisible(true);
        this.stop();
    }//GEN-LAST:event_MainMenuMouseReleased

    private void ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseReleased
        Hasil.setVisible(false);
        Bintang.setVisible(false);
        Exit.setVisible(false);
        WaktuGameHasil.setVisible(false);
        Next.setVisible(false);
        
    }//GEN-LAST:event_ExitMouseReleased

    private void NextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseReleased
        if(bintang>0){
            lvl.UpdateLevel(quizke, bintang);
            dispose();
        }
        else{
        lvl.UpdateLevel(quizke, 4);
        dispose();
        }
    }//GEN-LAST:event_NextMouseReleased

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlasNyawa;
    private javax.swing.JLabel AlasTextField;
    private javax.swing.JLabel AlasTimer;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Bintang;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Go;
    private javax.swing.JLabel Hasil;
    private javax.swing.JLabel MainMenu;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel Nyawa1;
    private javax.swing.JLabel Nyawa2;
    private javax.swing.JLabel Nyawa3;
    private javax.swing.JLabel Papan;
    private javax.swing.JLabel Quiz1;
    private javax.swing.JLabel Quiz10;
    private javax.swing.JLabel Quiz2;
    private javax.swing.JLabel Quiz3;
    private javax.swing.JLabel Quiz4;
    private javax.swing.JLabel Quiz5;
    private javax.swing.JLabel Quiz6;
    private javax.swing.JLabel Quiz7;
    private javax.swing.JLabel Quiz8;
    private javax.swing.JLabel Quiz9;
    private javax.swing.JTextField TextField;
    private javax.swing.JLabel WaktuGame;
    private javax.swing.JLabel WaktuGameHasil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
