/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prefixadventure;

import AppPackage.AnimationClass;
import javax.swing.ImageIcon;

/**
 *
 * @author Muhamad Dio
 */
public class SelectLevel extends javax.swing.JFrame {

    /**
     * Creates new form SelectLevel
     */
    public SelectLevel() {
        initComponents();
        
        Kotak2.setVisible(false);
        Kotak3.setVisible(false);
        Kotak4.setVisible(false);
        Kotak5.setVisible(false);
        Kotak6.setVisible(false);
        Kotak7.setVisible(false);
        Kotak8.setVisible(false);
        Kotak9.setVisible(false);
        Kotak10.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Kotak12 = new javax.swing.JLabel();
        Kotak13 = new javax.swing.JLabel();
        Kotak14 = new javax.swing.JLabel();
        Kotak15 = new javax.swing.JLabel();
        Kotak11 = new javax.swing.JLabel();
        Kotak7 = new javax.swing.JLabel();
        Kotak8 = new javax.swing.JLabel();
        Kotak9 = new javax.swing.JLabel();
        Kotak10 = new javax.swing.JLabel();
        Kotak6 = new javax.swing.JLabel();
        Kotak2 = new javax.swing.JLabel();
        Kotak3 = new javax.swing.JLabel();
        Kotak4 = new javax.swing.JLabel();
        Kotak5 = new javax.swing.JLabel();
        Kotak1 = new javax.swing.JLabel();
        Bintang15 = new javax.swing.JLabel();
        Bintang14 = new javax.swing.JLabel();
        Bintang13 = new javax.swing.JLabel();
        Bintang12 = new javax.swing.JLabel();
        Bintang11 = new javax.swing.JLabel();
        Bintang10 = new javax.swing.JLabel();
        Bintang9 = new javax.swing.JLabel();
        Bintang8 = new javax.swing.JLabel();
        Bintang7 = new javax.swing.JLabel();
        Bintang6 = new javax.swing.JLabel();
        Bintang5 = new javax.swing.JLabel();
        Bintang4 = new javax.swing.JLabel();
        Bintang3 = new javax.swing.JLabel();
        Bintang2 = new javax.swing.JLabel();
        Bintang1 = new javax.swing.JLabel();
        ComingSoon3 = new javax.swing.JLabel();
        ComingSoon2 = new javax.swing.JLabel();
        ComingSoon1 = new javax.swing.JLabel();
        Nomor1 = new javax.swing.JLabel();
        Nomor2 = new javax.swing.JLabel();
        Nomor3 = new javax.swing.JLabel();
        Nomor4 = new javax.swing.JLabel();
        Nomor5 = new javax.swing.JLabel();
        Nomor6 = new javax.swing.JLabel();
        Nomor7 = new javax.swing.JLabel();
        Nomor8 = new javax.swing.JLabel();
        Nomor9 = new javax.swing.JLabel();
        Nomor10 = new javax.swing.JLabel();
        Nomor11 = new javax.swing.JLabel();
        Nomor12 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Level = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prefix Adventure");

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Kotak12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Kotak12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 690, 130, 130));

        Kotak13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Kotak13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 690, 130, 130));

        Kotak14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Kotak14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 690, 130, 130));

        Kotak15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Kotak15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 690, 130, 130));

        Kotak11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Kotak11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 690, 119, 130));

        Kotak7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak7MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 130, 130));

        Kotak8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak8MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 130, 130));

        Kotak9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak9MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 130, 130));

        Kotak10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak10MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 130, 130));

        Kotak6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak6MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 119, 130));

        Kotak2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak2MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 130, 130));

        Kotak3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak3MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 130, 130));

        Kotak4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak4MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 350, 130, 130));

        Kotak5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak5MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 130, 130));

        Kotak1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kotak1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kotak1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kotak1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kotak1MouseReleased(evt);
            }
        });
        jPanel1.add(Kotak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 119, 130));

        Bintang15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang15, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 765, 119, 63));

        Bintang14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang14, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 765, 119, 63));

        Bintang13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang13, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 765, 119, 63));

        Bintang12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 765, 119, 63));

        Bintang11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 765, 119, 63));

        Bintang10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang10, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 595, 119, 63));

        Bintang9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang9, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 595, 119, 63));

        Bintang8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang8, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 595, 119, 63));

        Bintang7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 595, 119, 63));

        Bintang6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 595, 119, 63));

        Bintang5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang5, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 425, 119, 63));

        Bintang4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 425, 119, 63));

        Bintang3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 425, 119, 63));

        Bintang2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 425, 119, 63));

        Bintang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bintang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bintang0.png"))); // NOI18N
        jPanel1.add(Bintang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 425, 119, 63));

        ComingSoon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComingSoon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(ComingSoon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 90, 65));

        ComingSoon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComingSoon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(ComingSoon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 90, 65));

        ComingSoon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComingSoon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(ComingSoon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 700, 90, 65));

        Nomor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/1.png"))); // NOI18N
        jPanel1.add(Nomor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 79, 65));

        Nomor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 79, 65));

        Nomor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 360, 79, 65));

        Nomor4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 360, 79, 65));

        Nomor5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 79, 65));

        Nomor6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 79, 65));

        Nomor7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 79, 65));

        Nomor8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 530, 79, 65));

        Nomor9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 530, 79, 65));

        Nomor10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, 90, 65));

        Nomor11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 700, 79, 65));

        Nomor12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nomor12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Gebok.png"))); // NOI18N
        jPanel1.add(Nomor12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, 79, 65));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Back.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 66, 94));

        Level.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/SelectLevel.png"))); // NOI18N
        jPanel1.add(Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1280, 1024));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/SellectLevel_BG.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1024));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new Start().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked

    private void Kotak1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak1MouseClicked
      
    }//GEN-LAST:event_Kotak1MouseClicked

    private void Kotak1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak1MouseReleased
        Game game = new Game(this,1);
        game.setVisible(true);
        
    }//GEN-LAST:event_Kotak1MouseReleased

    private void Kotak2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak2MouseReleased
        Game game = new Game(this,2);
        game.setVisible(true);
        
    }//GEN-LAST:event_Kotak2MouseReleased

    private void Kotak3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak3MouseReleased
        Game game = new Game(this,3);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak3MouseReleased

    private void Kotak4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak4MouseReleased
        Game game = new Game(this,4);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak4MouseReleased

    private void Kotak5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak5MouseReleased
        Game game = new Game(this,5);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak5MouseReleased

    private void Kotak6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak6MouseReleased
        Game game = new Game(this,6);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak6MouseReleased

    private void Kotak7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak7MouseReleased
        Game game = new Game(this,7);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak7MouseReleased

    private void Kotak8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak8MouseReleased
        Game game = new Game(this,8);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak8MouseReleased

    private void Kotak9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak9MouseReleased
        Game game = new Game(this,9);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak9MouseReleased

    private void Kotak10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kotak10MouseReleased
        Game game = new Game(this,10);
        game.setVisible(true);
    }//GEN-LAST:event_Kotak10MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectLevel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Bintang1;
    private javax.swing.JLabel Bintang10;
    private javax.swing.JLabel Bintang11;
    private javax.swing.JLabel Bintang12;
    private javax.swing.JLabel Bintang13;
    private javax.swing.JLabel Bintang14;
    private javax.swing.JLabel Bintang15;
    private javax.swing.JLabel Bintang2;
    private javax.swing.JLabel Bintang3;
    private javax.swing.JLabel Bintang4;
    private javax.swing.JLabel Bintang5;
    private javax.swing.JLabel Bintang6;
    private javax.swing.JLabel Bintang7;
    private javax.swing.JLabel Bintang8;
    private javax.swing.JLabel Bintang9;
    private javax.swing.JLabel ComingSoon1;
    private javax.swing.JLabel ComingSoon2;
    private javax.swing.JLabel ComingSoon3;
    private javax.swing.JLabel Kotak1;
    private javax.swing.JLabel Kotak10;
    private javax.swing.JLabel Kotak11;
    private javax.swing.JLabel Kotak12;
    private javax.swing.JLabel Kotak13;
    private javax.swing.JLabel Kotak14;
    private javax.swing.JLabel Kotak15;
    private javax.swing.JLabel Kotak2;
    private javax.swing.JLabel Kotak3;
    private javax.swing.JLabel Kotak4;
    private javax.swing.JLabel Kotak5;
    private javax.swing.JLabel Kotak6;
    private javax.swing.JLabel Kotak7;
    private javax.swing.JLabel Kotak8;
    private javax.swing.JLabel Kotak9;
    private javax.swing.JLabel Level;
    private javax.swing.JLabel Nomor1;
    private javax.swing.JLabel Nomor10;
    private javax.swing.JLabel Nomor11;
    private javax.swing.JLabel Nomor12;
    private javax.swing.JLabel Nomor2;
    private javax.swing.JLabel Nomor3;
    private javax.swing.JLabel Nomor4;
    private javax.swing.JLabel Nomor5;
    private javax.swing.JLabel Nomor6;
    private javax.swing.JLabel Nomor7;
    private javax.swing.JLabel Nomor8;
    private javax.swing.JLabel Nomor9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public void UpdateLevel(int lvl, int bintang){
        
        switch(lvl){

            case 1 :
                if(bintang==4){
                    Game game = new Game(this,1);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang1.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/2.png"));
                    Nomor2.setIcon(IZ);
                    Kotak2.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang1.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/2.png"));
                    Nomor2.setIcon(IZ);
                    Kotak2.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang1.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/2.png"));
                    Nomor2.setIcon(IZ);
                    Kotak2.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang1.setIcon(II);
                }
                
                break;
                
            case 2 :
                if(bintang==4){
                    Game game = new Game(this,2);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang2.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/3.png"));
                    Nomor3.setIcon(IZ);
                    Kotak3.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang2.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/3.png"));
                    Nomor3.setIcon(IZ);
                    Kotak3.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang2.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/3.png"));
                    Nomor3.setIcon(IZ);
                    Kotak3.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang2.setIcon(II);
                }
                
                break;
                
            case 3 :
                if(bintang==4){
                    Game game = new Game(this,3);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang3.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/4.png"));
                    Nomor4.setIcon(IZ);
                    Kotak4.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang3.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/4.png"));
                    Nomor4.setIcon(IZ);
                    Kotak4.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang3.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/4.png"));
                    Nomor4.setIcon(IZ);
                    Kotak4.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang3.setIcon(II);
                }
                
                break;
                
            case 4 :
                if(bintang==4){
                    Game game = new Game(this,4);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang4.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/5.png"));
                    Nomor5.setIcon(IZ);
                    Kotak5.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang4.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/5.png"));
                    Nomor5.setIcon(IZ);
                    Kotak5.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang4.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/5.png"));
                    Nomor5.setIcon(IZ);
                    Kotak5.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang4.setIcon(II);
                }
                
                break;
                
            case 5 :
                if(bintang==4){
                    Game game = new Game(this,5);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang5.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/6.png"));
                    Nomor6.setIcon(IZ);
                    Kotak6.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang5.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/6.png"));
                    Nomor6.setIcon(IZ);
                    Kotak6.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang5.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/6.png"));
                    Nomor6.setIcon(IZ);
                    Kotak6.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang5.setIcon(II);
                }
                
                break;
                
            case 6 :
                if(bintang==4){
                    Game game = new Game(this,6);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang6.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/7.png"));
                    Nomor7.setIcon(IZ);
                    Kotak7.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang6.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/7.png"));
                    Nomor7.setIcon(IZ);
                    Kotak7.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang6.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/7.png"));
                    Nomor7.setIcon(IZ);
                    Kotak7.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang6.setIcon(II);
                }
                
                break;
                
            case 7 :
                if(bintang==4){
                    Game game = new Game(this,7);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang7.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/8.png"));
                    Nomor8.setIcon(IZ);
                    Kotak8.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang7.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/8.png"));
                    Nomor8.setIcon(IZ);
                    Kotak8.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang7.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/8.png"));
                    Nomor8.setIcon(IZ);
                    Kotak8.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang7.setIcon(II);
                }
                
                break;
                
            case 8 :
                if(bintang==4){
                    Game game = new Game(this,8);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang8.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/9.png"));
                    Nomor9.setIcon(IZ);
                    Kotak9.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang8.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/9.png"));
                    Nomor9.setIcon(IZ);
                    Kotak9.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang8.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/9.png"));
                    Nomor9.setIcon(IZ);
                    Kotak9.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang8.setIcon(II);
                }
                
                break;
                
            case 9 :
                if(bintang==4){
                    Game game = new Game(this,9);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang9.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/10.png"));
                    Nomor10.setIcon(IZ);
                    Kotak10.setVisible(true);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang9.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/10.png"));
                    Nomor10.setIcon(IZ);
                    Kotak10.setVisible(true);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang9.setIcon(II);
                    ImageIcon IZ = new ImageIcon(getClass().getResource("/Button/10.png"));
                    Nomor10.setIcon(IZ);
                    Kotak10.setVisible(true);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang9.setIcon(II);
                }
                
                break;
                
            case 10 :
                if(bintang==4){
                    Game game = new Game(this,9);
                    game.setVisible(true);
                }
                else if(bintang==3){
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang3.png"));
                    Bintang10.setIcon(II);
                }
                else if(bintang==2){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang2.png"));
                    Bintang10.setIcon(II);
                }
                else if(bintang==1){
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang1.png"));
                    Bintang10.setIcon(II);
                }
                else{
                    
                    ImageIcon II = new ImageIcon(getClass().getResource("/Button/Bintang0.png"));
                    Bintang10.setIcon(II);
                }
                
                break;
                
        }
}
}