/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prefixadventure;

import AppPackage.AnimationClass;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
/**
 *
 * @author Muhamad Dio
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        
        AnimationClass anim = new AnimationClass();
        //Animasi Main Title
        anim.jLabelYDown(MainTitle.getY(), 130, 2, 10, MainTitle);
        //Animasi Main Title 2
        anim.jLabelYDown(MainTitle2.getY(), 450, 2, 10, MainTitle2);
        //Animasi Play Button
        anim.jLabelYUp(Play.getY(), 690, 2, 10, Play);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Play = new javax.swing.JLabel();
        MainTitle2 = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prefix Adventure");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Play_1.png"))); // NOI18N
        Play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayMouseExited(evt);
            }
        });
        jPanel1.add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1500, 377, 173));

        MainTitle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/ByDio.png"))); // NOI18N
        jPanel1.add(MainTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -1000, 471, 236));

        MainTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/MainTitle.png"))); // NOI18N
        jPanel1.add(MainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -500, 1000, 419));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/StartBG.png"))); // NOI18N
        BG.setAlignmentY(0.0F);
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseEntered

    }//GEN-LAST:event_PlayMouseEntered

    private void PlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseExited

    }//GEN-LAST:event_PlayMouseExited

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        new SelectLevel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel MainTitle2;
    private javax.swing.JLabel Play;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
